### ISSUE TITLE
What to use for the website

### ISSUE THREAD

**Issue by fbt** [hypeirc/website#1]
Does a static site sound good?

I'm currently working on finishing the second version of zlog, which could be just dumped here with the content so that you can clone, modify, regenerate and push all in one repo.

**Comment by prurigro** [comment]
At minimum we should have a what's what explaining how the IRC network is run and list the servers, and a static site could easily hold all that. That said, if we were willing to go dynamic, it might be useful to have a status indicator showing if a given server is online, and if it is, maybe show how long it's been online? Would an ircd map be providing more information than we need/should?

**Comment by dansup** [comment]
Closing this because we decided to use @fbt zlog static site generator
