### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by dansup** [hypeirc/website#2]
I have designed a couple of logos for hypeirc, feedback please @prurigro and @fbt !

![hypeirc-logos](https://cloud.githubusercontent.com/assets/877217/12936094/377f209c-cf58-11e5-8d5d-576d7d44c5c3.png)

**Comment by dansup** [comment]
We can always adjust the colours to match the website, I think either this purple or a yellow/grey mix would be ideal.

**Comment by fbt** [comment]
Or we can match the site to the logo :)

I like the right one.
